services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/data  # Persists your vector DB to your local machine
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    

  redis:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data   # Persists your queue tasks if Redis restarts
    

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    

  fastapi:
    build: .
    container_name: rag_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      # Removed postgres dependency when using RDS
      chromadb:
        condition: service_started
      redis:
        condition: service_started
    

  worker:
    image: pdf-worker:latest
    container_name: rag_worker
    env_file:
      - .env.worker
    depends_on:
      - chromadb
      - redis
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./unstructured_cache:/root/.cache/huggingface
    
  transcriber:
    image: faster-whisper-image
    container_name: faster-whisper
    env_file:
      - .env.audio
    depends_on:
      - chromadb
      - redis
      - postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    volumes:
      - ./input:/data/input
      - ./output:/data/output
      - ./model_cache:/root/.cache/huggingface
      - ./torch_cache:/root/.cache/torch

volumes:
  postgres_data: